version: '3.8'

services:
  shopper-lens-dash:
    build: .
    ports:
      - "3005:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Mount video files from host
      - ./public:/app/public:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
